### ISSUE TITLE
AANE_fun: ValueError: matrix type must be 'f', 'd', 'F', or 'D'

### ISSUE THREAD

**Issue by calliwen** [xhuang31/AANE_Python#1]
emb_matrix = AANE_fun(data_net_matrix, data_attr_matrix, d = 128  )

when I use AANE to get the data_attr_net_matrix  embedding matrix, is wrong.

**Comment by calliwen** [comment]
I solved this problem by mapping  elem.type from long to float for the net_matrix and attr_matrix.

def change_elemType(net_matrix):
    net_matrix_list = net_matrix.tolist()
    node_num = len( net_matrix_list )
    for index in range( node_num ):
        net_matrix_list[index] = list(map(float, net_matrix_list[index]))
    return np.matrix( net_matrix_list )

**Comment by xhuang31** [comment]
Thanks @calliwen. I didn't pay attention to this. All my data is loaded from .mat files, with the default format as float.
